### ISSUE TITLE
引入axios在小程序中，构建后提示util未找到

### ISSUE THREAD

**Issue by FliPPeDround** [jaluik/axios-wechat-adapter#1]
Error: module 'miniprogram_npm/combined-stream/util.js' is not defined, require args is 'util'
这似乎是一个node的包，
有什么解决方案吗？

**Comment by jaluik** [comment]
你是怎么引入的？

**Comment by FliPPeDround** [comment]
npm i axios axios-wechat-adapter
然后用微信小程序的构建npm
import axios from ‘’axios‘
import adapter from ’axios-wechat-adapter‘
